### ISSUE TITLE
Include build script for executable

### ISSUE THREAD

**Issue by ghost** [Teraskull/PyDebloatX#16]
Include build script or directions for build in README

**Comment by Teraskull** [comment]
A single executable is not possible, since it needs access to the external CSS script. The whole process involves creating an `.exe` file with `auto-py-to-exe` in a virtual environment, then removing unused files from the build folder, to shrink the size, then running an `NSI` script to create an installer. Without these steps, it would be impossible to get the installer to be 15mb, instead of around 100mb. So there is no easy way to write down the whole setup, without using my personal file paths. I will try to write a simple `auto-py-to-exe` instruction

**Comment by ghost** [comment]
Sorry, I should have been more specific, mean't some general instruction to build the executable for [Releases](https://github.com/Teraskull/PyDebloatX/releases).

>  I will try to write a simple auto-py-to-exe instruction
Thanks.

**Comment by Teraskull** [comment]
@Autotonic Done! Please check out the `setup.bat` in the develop branch. Once you test it this issue can be closed.
