### ISSUE TITLE
Virus  alert

### ISSUE THREAD

**Issue by ghost** [Teraskull/PyDebloatX#56]
I created a portable exe file. I scanned for virus total.
![vırustotal](https://user-images.githubusercontent.com/84670981/132106432-2ca38bb9-49ba-4f7b-93ef-23120c48c63b.jpg)

**Comment by Teraskull** [comment]
Hi, thanks for this report,

There is nothing weird about it. Your own built executable is not signed with a certificate, and because PyDebloatX performs "suspicious" operations like checking the file size and deleting built-in software, of course it would be flagged. The last released executables for 1.12.0 include VirusTotal scans, and are signed with my developer certificate.

Here is the result for my self-signed executable: [PyDebloatX_setup.exe](https://www.virustotal.com/gui/file/f4a8f31c5f8f3936bdbd5e01e1429ce544a962716de7c357fab756d212d4fd07/detection)
Which has no flags.

Python executables often get flagged on VirusTotal for some reason. I will close this issue because there is really not a lot I can do, except for obfuscating the code with PyArmor or something, which is something I wouldn't do myself.

If you want to use the officially released executables, check the "Digital Signatures" in the file properties, to verify it was signed by me on release date:

![image](https://user-images.githubusercontent.com/24798198/132217493-8dc7f92e-e8ed-4a04-af15-c83cfe42123b.png)

**Comment by ghost** [comment]
very thanks I understand.  ,Good work
